[proxmox]
pve01 ansible_host=192.168.20.11
pve02 ansible_host=192.168.20.12
pve03 ansible_host=192.168.20.13

[ipmi]
ipmi01 ansible_host=192.168.30.11
ipmi02 ansible_host=192.168.30.12
ipmi03 ansible_host=192.168.30.13

[all:vars]
ansible_user=root
# Prefer SSH keys; if using password, set via --ask-pass or vault.
